title : Marco Petolicchio Personal Webspace
author :
    name : Marco Petolicchio
    image: assets/img/pic-72.jpg
# Sass settings
sass:
    sass_dir: assets/css
    style: :compressed

# Breadcrumbs

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Set collections
collections:
  activity:
    title : News & Events 
  research:
    title : Research activity 
  projects :
    title : Projects 
  teaching :
    title : Course materials 
