title : marcopetolicchio.com
author :
  name : Marco Petolicchio
  image: assets/img/pic-72.jpg
  headline: Linguist & tech enthusiast
baseurl: "http://marcopetolicchio.com"
# Sass settings
sass:
  sass_dir: assets/css
  style: compressed

# Set collections
collections:
  activity:
    output : true
    title : News & Events 
  research:
    output : true
    title : Research activity 
    layout: default
  projects :
    output : true
    title : Projects 
  teaching :
    output : true
    title : Course materials 
plugins:
  - jekyll-sitemap
  - jekyll-feed
lang: en
