theme: jekyll-theme-minimal
title : Marco Petolicchio Personal Webspace
author :
    name : Marco Petolicchio
    email : marco.petolicchio@gmail.com
    phone: 393279594722
    github : p-marco
    facebook: PetolicchioMarco
    linkedin: marcopetolicchio
    academia: upol.academia.edu/MarcoPetolicchio
    medium: marcopetolicchio
    skype: petolicchiomarco@tiscali.it
    website: marcopetolicchio.com