theme: jekyll-theme-minimal
title : Marco Petolicchio Personal Webspace
author :
    name : Marco Petolicchio
    email : marco.petolicchio@gmail.com
    github : p-marco
    facebook: PetolicchioMarco
    linkedin: MarcoPetolicchio
    academia: upol.academia.edu/MarcoPetolicchio
